# mybatis plus 中的连接配置
spring:
  datasource:
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:mysql://42.194.140.137:16888/db1?characterEncoding=utf-8&useSSL=false
          username: root
          password: $10$ogvUqZ1Z
        slave_1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:mysql://42.194.140.137:16888/db2?characterEncoding=utf-8&useSSL=false
          username: root
          password: $10$ogvUqZ1Z

#  mvc:
#    static-path-pattern: /static/**
# 日志打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl